### ISSUE TITLE
how to train with this net and my data?

### ISSUE THREAD

**Issue by BachTuan975** [titu1994/keras-efficientnets#11]
how to train with this net and my data? Can you give me the example code? Thanks

**Comment by titu1994** [comment]
There are several available tutorials on transfer learning using Keras applications. Please refer to them directly. All concepts there will apply here.

**Comment by BachTuan975** [comment]
Thanks. I have trained with b5. so can i train with b6,b7 now?

**Comment by titu1994** [comment]
From scratch? Sure if you want to. However, they don't have pretrained weights so performance might be quite poor.

**Comment by BachTuan975** [comment]
I trained b5 with the input size of 300x300. As far as I understand, your code will load the weight of b3. So why don't we use the weight of b5 for b7?

**Comment by titu1994** [comment]
B5 and B7 don't have the same hyperparameters, so I can't load B5 weights for B7 model.

**Comment by BachTuan975** [comment]
Oh, so, I got it. Thank you for your support
