### ISSUE TITLE
EfficientNetB3 meets error when load pretrained weights

### ISSUE THREAD

**Issue by lan2720** [titu1994/keras-efficientnets#2]
Thanks a lot! I can use EfficientNetB0 perfectly now. But when I change the base model to EfficientNetB3,  an error raises:
```
Traceback (most recent call last):
  File "/data1/jiananwang/anaconda3/envs/fashion/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1 and 1536. Shapes are [1,1,384,1535] and [1536,384,1,1]. for 'Assign_489' (op: 'Assign') with input shapes: [1,1,384,1535], [1536,384,1,1].
```
I also tried EfficientNetB1, EfficientNetB2, similar error. Could you check it?

**Comment by titu1994** [comment]
Good catch. Could you pull from master and see if the latest fix https://github.com/titu1994/keras-efficientnets/commit/15e784a0fa880f47c753c0f6ae6131d4d614ccfd corrects this ?

**Comment by lan2720** [comment]
@titu1994 Yes, It works now. Thanks a lot!
