### ISSUE TITLE
load_model gives ValueError: Unknown initializer

### ISSUE THREAD

**Issue by tvdhout** [titu1994/keras-efficientnets#3]
When saving a model to h5 file and trying to load it with keras.models.load_model, I get the following error.
ValueError: Unknown initializer: EfficientNetConvInitializer
Any idea how to fix this? any help is appreciated, thanks!

**Comment by tvdhout** [comment]
fixed, needed
from keras_efficientnet import custom_objects

in the test file

**Comment by titu1994** [comment]
This shouldn't be needed actually. The efficientnet.py script imports custom_objects, which automatically should register the custom objects. 

Could you provide details on earlier whether you were unable to inport the objects?

**Comment by tvdhout** [comment]
I used
```from keras_efficientnets import EfficientNetB4```
only (as stated in your README) when creating / training the network, so I didn't import the whole efficientnet.py file. That's probably why it didn't run the code in there.

**Comment by titu1994** [comment]
`from keras_efficientnets import EfficientNetB4` actually does import custom_objects as they require the initializers and Swish activation function to build the model. 

Its an interesting issue, I'll see if I can make it automatic somehow. Thanks for your help.

**Comment by tvdhout** [comment]
Note that my training / testing scripts are in different files. I train my model in train.py and save it, then load it in test.py. The `from keras_efficientnets import EfficientNetB4` was only in my train.py file. Adding `from keras_efficientnet import custom_objects` to my test.py file solved the error.

I just tested it with `keras_efficientnets import EfficientNetB4` in my test.py file, instead of `from keras_efficientnet import custom_objects`, and that works too, so you're right, it does run the custom_objects code when importing just EfficientNetB4. Just need to make sure it's also imported in the file where the model is loaded.

**Comment by titu1994** [comment]
Good catch. Yes, without any import from the library, it won't register the custom objects.

**Comment by BachTuan975** [comment]
I have the same error as you:
"ValueError: Unknown initializer: EfficientNetConvInitializer"
I also tried.
from keras_efficientnet import custom_objects
  But there is no module 'keras_efficientnet'
I install the library using "pip install keras_efficientnets"
Did I install missing?

**Comment by titu1994** [comment]
It's keras_efficientnet**s**.

**Comment by BachTuan975** [comment]
right. and I see custom_objects.py status is Prepare for pypi support. Maybe I installed missing.
I tried
from keras_efficientnets import EfficientNetB5, preprocess_input, custom_objects
But
ValueError: Unknown initializer: EfficientNetConvInitializer

**Comment by BachTuan975** [comment]
I found the error.
I used it before
from tensorflow.python.keras.models import load_model
I replaced with
from load_model import keras.models
and my test file has run
Thank you! @titu1994
