### ISSUE TITLE
No attribute 'swish' error

### ISSUE THREAD

**Issue by jannaescur** [titu1994/keras-efficientnets#9]
I get the following error:
`AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'swish'`

Tensorflow version: 1.4.0 (GPU, installed before your library)
Keras version: 2.2.4

I have imported the model: `from keras_efficientnets import EfficientNetB4`
This should import custom_objects too, right?

Any idea of what can be happening? Thanks

**Comment by titu1994** [comment]
Update your tensorflow version. TF.nn.swish was not added in TF 1.4
